config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :dashboards, path: '' do
    get '/monthly', to: 'dashboard#monthly'
    get '/annual', to: 'dashboard#annual'
  end
  # devise_for :users, class_name: 'Users::User'
  devise_for :users, class_name: 'Users::User', path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
                     controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations'
                     }

  namespace :financial_objects, path: '' do
    resources :incomes, :payment_methods, :expenses, :goals
  end

  namespace :categories do
    resources :category_expenses, path: 'expenses'
    resources :category_incomes, path: 'incomes'
  end
  # namespace :categories do
  #   resources :category_incomes
  # end
  namespace :users do
    resources :wallets
  end
  # namespace :financial_objects do
  #   resources :goals
  # end
  # namespace :financial_objects do
  #   resources :payment_methods
  # end
  # namespace :financial_objects do
  #   resources :expenses
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/financial_objects.rb
module FinancialObjects
  def self.table_name_prefix
    'financial_objects_'
  end
end

app/models/financial_objects/expense.rb
# == Schema Information
#
# Table name: financial_objects_expenses
#
#  id                :bigint           not null, primary key
#  currency          :decimal(8, 2)
#  date              :date
#  description       :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  category_id       :bigint           not null
#  payment_method_id :bigint           not null
#  wallet_id         :bigint           not null
#
# Indexes
#
#  index_financial_objects_expenses_on_category_id        (category_id)
#  index_financial_objects_expenses_on_payment_method_id  (payment_method_id)
#  index_financial_objects_expenses_on_wallet_id          (wallet_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories_category_expenses.id)
#  fk_rails_...  (payment_method_id => financial_objects_payment_methods.id)
#  fk_rails_...  (wallet_id => users_wallets.id)
#
module FinancialObjects
  class Expense < FinancialObject
    validates :description, presence: true
    belongs_to :category, class_name: 'Categories::CategoryExpense'
    belongs_to :payment_method, class_name: 'FinancialObjects::PaymentMethod'
    belongs_to :wallet, class_name: 'Users::Wallet'
  end
end

app/models/financial_objects/financial_object.rb
module FinancialObjects
  class FinancialObject < ApplicationRecord
    self.abstract_class = true
  end
end

app/models/financial_objects/goal.rb
# == Schema Information
#
# Table name: financial_objects_goals
#
#  id          :bigint           not null, primary key
#  currency    :decimal(, )
#  description :string
#  due_date    :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  wallet_id   :bigint           not null
#
# Indexes
#
#  index_financial_objects_goals_on_wallet_id  (wallet_id)
#
# Foreign Keys
#
#  fk_rails_...  (wallet_id => users_wallets.id)
#
module FinancialObjects
  class Goal < ApplicationRecord
    belongs_to :wallet
  end
end

app/models/financial_objects/income.rb
# == Schema Information
#
# Table name: financial_objects_incomes
#
#  id          :bigint           not null, primary key
#  currency    :decimal(8, 2)
#  date        :date
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  wallet_id   :bigint           not null
#
# Indexes
#
#  index_financial_objects_incomes_on_category_id  (category_id)
#  index_financial_objects_incomes_on_wallet_id    (wallet_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories_category_incomes.id)
#  fk_rails_...  (wallet_id => users_wallets.id)
#
module FinancialObjects
  class Income < FinancialObject
    belongs_to :category, class_name: 'Categories::CategoryIncome'
    belongs_to :wallet, class_name: 'Users::Wallet'
  end
end

app/models/financial_objects/payment_method.rb
# == Schema Information
#
# Table name: financial_objects_payment_methods
#
#  id          :bigint           not null, primary key
#  date        :date
#  description :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  wallet_id   :bigint           not null
#
# Indexes
#
#  index_financial_objects_payment_methods_on_wallet_id  (wallet_id)
#
# Foreign Keys
#
#  fk_rails_...  (wallet_id => users_wallets.id)
#
module FinancialObjects
  class PaymentMethod < ApplicationRecord
    belongs_to :wallet, class_name: 'Users::Wallet'
  end
end

app/controllers/financial_objects/expenses_controller.rb
module FinancialObjects
  class ExpensesController < ApplicationController
    before_action :set_financial_objects_expense, only: %i[show edit destroy]
    before_action :authenticate_user!

    # GET /financial_objects/expenses or /financial_objects/expenses.json
    def index
      @financial_objects_expenses = manager.index(current_user)
      @pagy, @financial_objects_expenses = pagy(@financial_objects_expenses)
    end

    # GET /financial_objects/expenses/1 or /financial_objects/expenses/1.json
    def show; end

    # GET /financial_objects/expenses/new
    def new
      @financial_objects_expense = FinancialObjects::Expense.new
    end

    # GET /financial_objects/expenses/1/edit
    def edit; end

    # POST /financial_objects/expenses or /financial_objects/expenses.json
    def create
      @financial_objects_expense = manager.create(financial_objects_expense_params, current_user)

      respond_to do |format|
        if @financial_objects_expense.valid?
          format.html { redirect_to @financial_objects_expense, notice: 'Expense was successfully created.' }
          format.json { render :show, status: :created, location: @financial_objects_expense }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @financial_objects_expense.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /financial_objects/expenses/1 or /financial_objects/expenses/1.json
    def update
      updated_succeeds, @financial_objects_expense = manager.update(params[:id], financial_objects_expense_params, current_user)

      respond_to do |format|
        if updated_succeeds
          format.html { redirect_to @financial_objects_expense, notice: 'Expense was successfully updated.' }
          format.json { render :show, status: :ok, location: @financial_objects_expense }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @financial_objects_expense.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /financial_objects/expenses/1 or /financial_objects/expenses/1.json
    def destroy
      @financial_objects_expense.destroy
      respond_to do |format|
        format.html { redirect_to financial_objects_expenses_url, notice: 'Expense was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def manager
      FinancialObjects::ExpenseManager.new
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_financial_objects_expense
      @financial_objects_expense = FinancialObjects::Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def financial_objects_expense_params
      params.require(:financial_objects_expense).permit(:description, :currency, :category_id, :payment_method_id, :date)
    end
  end
end

app/controllers/financial_objects/goals_controller.rb
class FinancialObjects::GoalsController < ApplicationController
  before_action :set_financial_objects_goal, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /financial_objects/goals or /financial_objects/goals.json
  def index
    @financial_objects_goals = FinancialObjects::Goal.all
  end

  # GET /financial_objects/goals/1 or /financial_objects/goals/1.json
  def show
  end

  # GET /financial_objects/goals/new
  def new
    @financial_objects_goal = FinancialObjects::Goal.new
  end

  # GET /financial_objects/goals/1/edit
  def edit
  end

  # POST /financial_objects/goals or /financial_objects/goals.json
  def create
    @financial_objects_goal = FinancialObjects::Goal.new(financial_objects_goal_params)

    respond_to do |format|
      if @financial_objects_goal.save
        format.html { redirect_to @financial_objects_goal, notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @financial_objects_goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @financial_objects_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financial_objects/goals/1 or /financial_objects/goals/1.json
  def update
    respond_to do |format|
      if @financial_objects_goal.update(financial_objects_goal_params)
        format.html { redirect_to @financial_objects_goal, notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @financial_objects_goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @financial_objects_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financial_objects/goals/1 or /financial_objects/goals/1.json
  def destroy
    @financial_objects_goal.destroy
    respond_to do |format|
      format.html { redirect_to financial_objects_goals_url, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financial_objects_goal
      @financial_objects_goal = FinancialObjects::Goal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def financial_objects_goal_params
      params.require(:financial_objects_goal).permit(:description, :currency, :due_date, :wallet_id)
    end
end

app/controllers/financial_objects/incomes_controller.rb
module FinancialObjects
  class IncomesController < ApplicationController
    before_action :set_financial_objects_income, only: %i[show edit destroy]
    before_action :authenticate_user!

    # GET /financial_objects/incomes or /financial_objects/incomes.json
    def index
      @financial_objects_incomes = manager.index(current_user)
      @pagy, @financial_objects_incomes = pagy(@financial_objects_incomes)
    end

    # GET /financial_objects/incomes/1 or /financial_objects/incomes/1.json
    def show; end

    # GET /financial_objects/incomes/new
    def new
      @financial_objects_income = FinancialObjects::Income.new
    end

    # GET /financial_objects/incomes/1/edit
    def edit; end

    # POST /financial_objects/incomes or /financial_objects/incomes.json
    def create
      @financial_objects_income = manager.create(financial_objects_income_params, current_user)

      respond_to do |format|
        if @financial_objects_income.valid?
          format.html { redirect_to @financial_objects_income, notice: 'Income was successfully created.' }
          format.json { render :show, status: :created, location: @financial_objects_income }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @financial_objects_income.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /financial_objects/incomes/1 or /financial_objects/incomes/1.json
    def update
      updated_succeeds, @financial_objects_income = manager.update(params[:id], financial_objects_income_params, current_user)

      respond_to do |format|
        if updated_succeeds
          format.html { redirect_to @financial_objects_income, notice: 'Income was successfully updated.' }
          format.json { render :show, status: :ok, location: @financial_objects_income }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @financial_objects_income.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /financial_objects/incomes/1 or /financial_objects/incomes/1.json
    def destroy
      @financial_objects_income.destroy
      respond_to do |format|
        format.html { redirect_to financial_objects_incomes_url, notice: 'Income was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def manager
      FinancialObjects::IncomeManager.new
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_financial_objects_income
      @financial_objects_income = FinancialObjects::Income.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def financial_objects_income_params
      params.require(:financial_objects_income).permit(:description, :currency, :category_id, :date)
    end
  end
end

app/controllers/financial_objects/payment_methods_controller.rb
class FinancialObjects::PaymentMethodsController < ApplicationController
  before_action :set_financial_objects_payment_method, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /financial_objects/payment_methods or /financial_objects/payment_methods.json
  def index
    @financial_objects_payment_methods = FinancialObjects::PaymentMethod.where(wallet_id: current_user.wallet_id)
  end

  # GET /financial_objects/payment_methods/1 or /financial_objects/payment_methods/1.json
  def show
  end

  # GET /financial_objects/payment_methods/new
  def new
    @financial_objects_payment_method = FinancialObjects::PaymentMethod.new
  end

  # GET /financial_objects/payment_methods/1/edit
  def edit
  end

  # POST /financial_objects/payment_methods or /financial_objects/payment_methods.json
  def create
    @financial_objects_payment_method = FinancialObjects::PaymentMethod.new(financial_objects_payment_method_params)

    respond_to do |format|
      if @financial_objects_payment_method.save
        format.html { redirect_to @financial_objects_payment_method, notice: "Payment method was successfully created." }
        format.json { render :show, status: :created, location: @financial_objects_payment_method }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @financial_objects_payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financial_objects/payment_methods/1 or /financial_objects/payment_methods/1.json
  def update
    respond_to do |format|
      if @financial_objects_payment_method.update(financial_objects_payment_method_params)
        format.html { redirect_to @financial_objects_payment_method, notice: "Payment method was successfully updated." }
        format.json { render :show, status: :ok, location: @financial_objects_payment_method }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @financial_objects_payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financial_objects/payment_methods/1 or /financial_objects/payment_methods/1.json
  def destroy
    @financial_objects_payment_method.destroy
    respond_to do |format|
      format.html { redirect_to financial_objects_payment_methods_url, notice: "Payment method was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financial_objects_payment_method
      @financial_objects_payment_method = FinancialObjects::PaymentMethod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def financial_objects_payment_method_params
      params.require(:financial_objects_payment_method).permit(:title, :description, :wallet_id, :date)
    end
end

app/helpers/financial_objects/expenses_helper.rb
module FinancialObjects::ExpensesHelper
end

app/helpers/financial_objects/goals_helper.rb
module FinancialObjects::GoalsHelper
end

app/helpers/financial_objects/incomes_helper.rb
module FinancialObjects::IncomesHelper
end

app/helpers/financial_objects/payment_methods_helper.rb
module FinancialObjects::PaymentMethodsHelper
end

app/views/financial_objects/expenses/_form.html.erb
<%= form_with(model: financial_objects_expense) do |form| %>
  <% if financial_objects_expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(financial_objects_expense.errors.count, "error") %> prohibited this financial_objects_expense from being saved:</h2>

      <ul>
        <% financial_objects_expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= render(InputTextField::Component.new(form: form,
                                             attribute_name: :description)) %>
  </div>

  <div class="field">
    <%= render(InputMoneyField::Component.new(form: form,
                                             attribute_name: :currency)) %>
  </div>

  <div class="field">
    <%#= form.label :category_id %>
    <%#= form.select :category_id, decorate(current_user).my_categories_incomes %>
    <%= render(SelectField::Component.new(form: form,
                                          attribute_name: :category_id,
                                          items: decorate(current_user).my_categories_expenses)) %>
  </div>

  <div class="field">
    <%#= form.label :payment_method_id %>
    <%#= form.select :payment_method_id, decorate(current_user).my_payment_methods %>
    <%= render(SelectField::Component.new(form: form,
                                          attribute_name: :payment_method_id,
                                          items: decorate(current_user).my_payment_methods)) %>
  </div>

  <div class="field">
    <%= render(DatePicker::Component.new(klass: form.object_name,
                                         form: form,
                                          attribute_name: :date,
                                         date: financial_objects_expense.date)) %>
  </div>

  <div class="actions">
    <%= render(SubmitFormButton::Component.new(form: form)) %>
  </div>
<% end %>

app/views/financial_objects/expenses/edit.html.erb
<h1 class="page-title mb-3">Editing Expense</h1>

<%= render 'form', financial_objects_expense: @financial_objects_expense %>

<%= link_to 'Show', @financial_objects_expense %> |
<%= link_to 'Back', financial_objects_expenses_path %>

app/views/financial_objects/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="mt-5 grid grid-cols-1 grid-rows-2 md:grid-cols-4">
  <div class="row-start-1 md:col-span-2 ">
    <h1 class="page-title">
      Expenses
    </h1>
  </div>

  <div class="row-start-2 md:row-start-2 md:col-span-2 md:col-start-3 block-inline">

      <div class="flex flex-row justify-center md:justify-end items-center">

        <div class="pl-5">
          <%= link_to new_financial_objects_expense_path,
                      class:"a-create-button" do %>
            + New Expense
          <% end %>
        </div>

      </div>

  </div>
</div>


<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
<% @financial_objects_expenses.each do |financial_objects_expense| %>
    <%= render(FinancialObjectCard::IndexComponent.new(financial_object: financial_objects_expense)) %>
<% end %>
</div>

<%=render(Pagination::PagyComponent.new(pagy:@pagy)) %>

app/views/financial_objects/expenses/new.html.erb
<h1 class="page-title mb-3">New Expense</h1>

<%= render 'form', financial_objects_expense: @financial_objects_expense %>

<%= link_to 'Back', financial_objects_expenses_path %>

app/views/financial_objects/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @financial_objects_expense.description %>
</p>

<p>
  <strong>Currency:</strong>
  <%= number_to_currency(@financial_objects_expense.currency) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @financial_objects_expense.category.title %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @financial_objects_expense.payment_method.title %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @financial_objects_expense.wallet_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= decorate(@financial_objects_expense.date).long %>
</p>

<%= link_to 'Edit', edit_financial_objects_expense_path(@financial_objects_expense) %> |
<%= link_to 'Back', financial_objects_expenses_path %>