config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :dashboards, path: '' do
    get '/monthly', to: 'dashboard#monthly'
    get '/annual', to: 'dashboard#annual'
  end
  # devise_for :users, class_name: 'Users::User'
  devise_for :users, class_name: 'Users::User', path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
                     controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations'
                     }

  namespace :financial_objects, path: '' do
    resources :incomes, :payment_methods, :expenses, :goals
  end

  namespace :categories do
    resources :category_expenses, path: 'expenses'
    resources :category_incomes, path: 'incomes'
  end
  # namespace :categories do
  #   resources :category_incomes
  # end
  namespace :users do
    resources :wallets
  end
  # namespace :financial_objects do
  #   resources :goals
  # end
  # namespace :financial_objects do
  #   resources :payment_methods
  # end
  # namespace :financial_objects do
  #   resources :expenses
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dashboards/annual_report.rb
module Dashboards
  class AnnualReport < Report
    attr_accessor :monthly_expense, :monthly_income
  end
end

app/models/dashboards/monthly_report.rb
module Dashboards
  class MonthlyReport < Report
    attr_accessor :month, :daily_expense, :daily_income

    def initialize(year, month)
      super(year)
      @month = month
    end
  end
end

app/models/dashboards/report.rb
module Dashboards
  class Report
    attr_accessor :year, :total_expenses_currency, :total_incomes_currency, :expenses_currency_by_categories, :incomes_currency_by_categories

    def initialize(year)
      super()
      @year = year
    end

  end
end

app/controllers/dashboards/dashboard_controller.rb
module Dashboards
  class DashboardController < ApplicationController
    before_action :set_month_and_year, only: :monthly
    before_action :set_year, only: :annual
    before_action :authenticate_user!

    def monthly
      @report = Dashboards::DashboardManager.new.show_monthly(current_user, @month, @year)
    end

    def annual
      @report = Dashboards::DashboardManager.new.show_annual(current_user, @year)
    end

    private

    def set_year
      @year = if params[:year].nil? || params[:year] == ''
                Time.now.strftime('%Y')
              else
                params[:year]
              end
    end

    def set_month_and_year
      @month_and_year = if params[:month].nil? || params[:month] == ''
                          Time.now.strftime('%Y-%m')
                        else
                          params[:month]
                        end
      @month = @month_and_year.split('-')[1].to_i
      @year = @month_and_year.split('-')[0].to_i
    end

  end
end

app/helpers/dashboards/dashboard_helper.rb
module Dashboards::DashboardHelper
end

app/views/dashboards/dashboard/annual.html.erb
<!--<h1>Dashboards::Dashboard#annual</h1>-->
<!--<p>Find me in app/views/dashboards/dashboard/annual.html.erb</p>-->
<!--<h1 type="year"><%#= @year %></h1>-->

<%#= form_with url: "/annual", method: :get do |form| %>
  <%#= form.label :year, "Choose a year:" %>
  <%#= form.select :year, (Time.now.year).downto(Time.now.year - 100).to_a, selected: @year %>
  <%#= form.submit "Go" %>
<%# end %>

<!--<h2>Income +<%#= number_to_currency(@report.total_incomes_currency) %></h2>-->

<!--<h2>Expense -<%#= number_to_currency(@report.total_expenses_currency) %></h2>-->

<%#
<!--  @data =     [-->
<!--    {name: "Incomes", data: { "Incomes": @report.total_incomes_currency }},-->
<!--    {name: "Expenses", data: { "Expenses": @report.total_expenses_currency }}-->
<!--  ]-->

%>
<!--<h2>Expenses vs Incomes</h2>-->
<%#= bar_chart @data, stacked: true%>

<%#  @data = [{:name=>"Income",  :data=> @report.monthly_income }, {:name=>"Expense",  :data=> @report.monthly_expense }] %>
<!--<h2>Total Expenses and Incomes every month</h2>-->
<%#= line_chart @data %>

<!--<br>-->
<!--<br>-->

<!--<h2>Expenses by category</h2>-->
<%#= pie_chart @report.expenses_currency_by_categories  %>

<!--<br>-->
<!--<br>-->

<!--<h2>Incomes by category</h2>-->
<%#= pie_chart @report.incomes_currency_by_categories %>



<div class="mt-5 grid grid-cols-1 grid-rows-2 md:grid-cols-4">
  <div class="row-start-1 md:col-span-2 ">
    <h1 class="text-4xl font-semibold text-gray-800 dark:text-white">
      <%= @year %>
    </h1>
  </div>

  <div class="row-start-2 md:row-start-2 md:col-span-2 md:col-start-3 block-inline">

    <%= form_with url: dashboards_annual_path, method: :get do |form| %>
      <div class="flex flex-row justify-center md:justify-end items-center">
        <%#= form.label :month, "Choose a month:" %>
        <div>
          <%#= form.month_field :month, class:"px-2 py-1 form-field", value: @month_and_year%>
          <%= render(SelectField::Component.new(form: form,
                                                title: false,
                                                attribute_name: :year,
                                                items: ((Time.now.year).downto(Time.now.year - 100)).to_a)) %>
          <%#= form.select :year, (Time.now.year).downto(Time.now.year - 100).to_a, class:"px-2 py-1 form-field", selected: @year %>
        </div>

        <div class="pl-5">
          <%= form.submit "Go!", class:"py-2 px-4 flex justify-center items-center text-white transition duration-500
    ease-in-out bg-blue-400 hover:bg-blue-500 transform hover:translate-y-1 hover:scale-110  w-12 h-12 rounded-lg
    hover:shadow-lg"%>
        </div>

      </div>
    <% end %>

  </div>
</div>

<div class="mt-5 grid grid-rows-12 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 lg:grid-rows-6 gap-8">

  <div class="row-span-1 col-span-1">
    <%= render FinanceCard::ComponentComponent.new(title:"Incomes",
                                                   currency:@report.total_incomes_currency,
                                                   type: "income") %>
  </div>

  <div class="row-span-1 col-span-1">
    <%= render FinanceCard::ComponentComponent.new(title:"Expenses",
                                                   currency:@report.total_expenses_currency,
                                                   type: "expense") %>
  </div>

  <div class="row-span-2 col-span-1 lg:col-start-3">
    <div class="item-bg">
      <h2 class="chart-title">Expenses by category</h2>
      <%= pie_chart @report.expenses_currency_by_categories, { thousands: ",", prefix: "$", round: 2, zeros: true }  %>
    </div>
  </div>

  <div class="row-start-3	md:row-start-2 row-span-1 col-span-1">
    <%= render FinanceCard::ComponentComponent.new(title:"Incomes",
                                                   currency:@report.total_incomes_currency,
                                                   type: "income") %>
  </div>

  <div class="row-start-4 md:row-start-2 row-span-1 col-span-1">
    <%= render FinanceCard::ComponentComponent.new(title:"Expenses",
                                                   currency:@report.total_expenses_currency,
                                                   type: "expense") %>
  </div>

  <div class="row-span-2 col-span-1 md:col-span-2 lg:col-start-1">
    <div class="item-bg">
      <h2 class="chart-title">Expenses vs Incomes</h2>
      <%= bar_chart [
                      {name: "Incomes", data: { "Incomes": @report.total_incomes_currency }},
                      {name: "Expenses", data: { "Expenses": @report.total_expenses_currency }}
                    ],
                    {stacked: true, thousands: ",", prefix: "$", round: 2, zeros: true }%>
    </div>
  </div>

  <div class="row-start-7 md:row-start-3 row-span-2 col-span-1 lg:col-start-3">
    <div class="item-bg">
      <h2 class="chart-title">Incomes by category</h2>
      <%= pie_chart @report.incomes_currency_by_categories, { thousands: ",", prefix: "$", round: 2, zeros: true } %>
    </div>
  </div>


  <div class="row-span-2 col-span-1 md:col-span-2 lg:col-span-3">
    <div class="item-bg">
      <h2 class="chart-title">Total Expenses and Incomes every day</h2>
      <%= line_chart [{:name=>"Income",  :data=> @report.monthly_income }, {:name=>"Expense",  :data=> @report.monthly_expense }],
                     { thousands: ",", prefix: "$", round: 2, zeros: true }%>
    </div>
  </div>

</div>

app/views/dashboards/dashboard/monthly.html.erb
<div class="mt-5 grid grid-cols-1 grid-rows-2 md:grid-cols-4">
  <div class="row-start-1 md:col-span-2 ">
    <h1 class="text-4xl font-semibold text-gray-800 dark:text-white">
      <%= decorate(@month).month_name %>, <%= @year %>
    </h1>
  </div>

  <div class="row-start-2 md:row-start-2 md:col-span-2 md:col-start-3 block-inline">

      <%= form_with url: dashboards_monthly_path, method: :get do |form| %>
      <div class="flex flex-row justify-center md:justify-end items-center">
        <%#= form.label :month, "Choose a month:" %>
        <div>
          <%= form.month_field :month, class:"px-2 py-2 form-field", value: @month_and_year%>
        </div>

        <div class="pl-5">
          <%= form.submit "Go!", class:"py-2 px-4 flex justify-center items-center text-white transition duration-500
    ease-in-out bg-blue-400 hover:bg-blue-500 transform hover:translate-y-1 hover:scale-110  w-12 h-12 rounded-lg
    hover:shadow-lg"%>
        </div>

      </div>
      <% end %>

  </div>
</div>

<div class="mt-5 grid grid-rows-12 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 lg:grid-rows-6 gap-8">

  <div class="row-span-1 col-span-1">
  <%= render FinanceCard::ComponentComponent.new(title:"Incomes",
                                                 currency:@report.total_incomes_currency,
                                                 type: "income") %>
  </div>

    <div class="row-span-1 col-span-1">
  <%= render FinanceCard::ComponentComponent.new(title:"Expenses",
                                                 currency:@report.total_expenses_currency,
                                                 type: "expense") %>
    </div>

  <div class="row-span-2 col-span-1 lg:col-start-3">
    <div class="item-bg">
      <h2 class="chart-title">Expenses by category</h2>
      <%= pie_chart @report.expenses_currency_by_categories, { thousands: ",", prefix: "$", round: 2, zeros: true }  %>
    </div>
  </div>

  <div class="row-start-3	md:row-start-2 row-span-1 col-span-1">
    <%= render FinanceCard::ComponentComponent.new(title:"Incomes",
                                                   currency:@report.total_incomes_currency,
                                                   type: "income") %>
  </div>

  <div class="row-start-4 md:row-start-2 row-span-1 col-span-1">
    <%= render FinanceCard::ComponentComponent.new(title:"Expenses",
                                                   currency:@report.total_expenses_currency,
                                                   type: "expense") %>
  </div>

  <div class="row-span-2 col-span-1 md:col-span-2 lg:col-start-1">
    <div class="item-bg">
      <h2 class="chart-title">Expenses vs Incomes</h2>
      <%= bar_chart [
                      {name: "Incomes", data: { "Incomes": (@report.total_incomes_currency) }},
                      {name: "Expenses", data: { "Expenses": (@report.total_expenses_currency) }}
                    ],
                    {stacked: true, thousands: ",", prefix: "$", round: 2, zeros: true }%>
    </div>
  </div>

  <div class="row-start-7 md:row-start-3 row-span-2 col-span-1 lg:col-start-3">
    <div class="item-bg">
      <h2 class="chart-title">Incomes by category</h2>
      <%= pie_chart @report.incomes_currency_by_categories, { thousands: ",", prefix: "$", round: 2, zeros: true } %>
    </div>
  </div>


  <%  @data1 = [{:name=>"Income",  :data=> @report.daily_income }, {:name=>"Expense",  :data=> @report.daily_expense }] %>
  <div class="row-span-2 col-span-1 md:col-span-2 lg:col-span-3">
    <div class="item-bg">
      <h2 class="chart-title">Total Expenses and Incomes every day</h2>
      <%= line_chart @data1, { thousands: ",", prefix: "$", round: 2, zeros: true }%>
    </div>
  </div>

</div>